# Generated by Django 3.2 on 2022-11-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0004_goodinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
    ]
